export const navItems = [
  { label: "Home", href: "/" },
  {
    label: "News",
    href: "/category/diplomacy",
    children: [
      { label: "Latest", href: "/category/diplomacy" },
      { label: "Breaking", href: "/search?q=breaking" },
      { label: "Global Brief", href: "/category/analysis" },
    ],
  },
  { label: "Diplomacy", href: "/category/diplomacy" },
  { label: "Foreign Policy", href: "/category/foreign-policy" },
  { label: "World", href: "/category/analysis" },
  {
    label: "Regions",
    href: "/countries",
    children: [
      { label: "South Asia", href: "/search?region=South+Asia" },
      { label: "East Asia", href: "/search?region=East+Asia" },
      { label: "North America", href: "/search?region=North+America" },
      { label: "Europe", href: "/search?region=Europe" },
    ],
  },
  { label: "Economy", href: "/category/economy" },
  { label: "Security", href: "/category/security" },
  { label: "Climate", href: "/category/climate" },
  { label: "Opinion", href: "/category/opinion" },
  { label: "Analysis", href: "/category/analysis" },
  { label: "Explainers", href: "/category/explainers" },
  {
    label: "Countries",
    href: "/countries",
    children: [
      { label: "All Countries", href: "/countries" },
      { label: "India", href: "/country/india" },
      { label: "China", href: "/country/china" },
      { label: "United States", href: "/country/united-states" },
      { label: "Japan", href: "/country/japan" },
    ],
  },
  {
    label: "Embassies",
    href: "/embassies",
    children: [
      { label: "Directory", href: "/embassies" },
      { label: "Embassy of India", href: "/embassy/indian-embassy-kathmandu" },
      { label: "Embassy of China", href: "/embassy/chinese-embassy-kathmandu" },
      { label: "U.S. Embassy", href: "/embassy/us-embassy-kathmandu" },
    ],
  },
  {
    label: "Organizations",
    href: "/organizations",
    children: [
      { label: "All Organizations", href: "/organizations" },
      { label: "United Nations", href: "/organization/united-nations" },
      { label: "World Bank", href: "/organization/world-bank" },
      { label: "SAARC", href: "/organization/saarc" },
      { label: "BIMSTEC", href: "/organization/bimstec" },
      { label: "IMF", href: "/organization/imf" },
    ],
  },
  { label: "Events", href: "/events" },
  { label: "Magazine", href: "/magazine" },
  { label: "Podcasts", href: "/podcasts" },
  { label: "Videos", href: "/videos" },
  { label: "Research", href: "/category/intelligence" },
  { label: "Membership", href: "/membership" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
